### ISSUE TITLE
Navbar always points to /dev/, regardless of current version

### ISSUE THREAD

**Issue by jni** [scikit-image/skimage-web#22]
Steps to reproduce:
- Navigate to http://scikit-image.org/docs/0.10.x/
- Click on Gallery, which points to http://scikit-image.org/docs/dev/auto_examples

Desired behaviour:
- Gallery should link to http://scikit-image.org/docs/0.10.x/auto_examples/

**Comment by stefanv** [comment]
Not the case for the last several releases, so we'll have fewer and fewer people hitting this issue.
