### ISSUE TITLE
New community guidelines breaks navigation

### ISSUE THREAD

**Issue by ahojnnes** [scikit-image/skimage-web#37]
See: http://scikit-image.org/community_guidelines.html, the search bar is not on the same line as the rest of the navigation any more.

**Comment by stefanv** [comment]
I don't see this in my browser.  Does anyone else?

**Comment by soupault** [comment]
I do (latest stable Chromium + Chrome):
![image](https://cloud.githubusercontent.com/assets/1315589/18242256/1d2852cc-735e-11e6-9be8-cc61ab411679.png)

**Comment by soupault** [comment]
Closed via https://github.com/scikit-image/scikit-image/pull/2287

**Comment by soupault** [comment]
Sorry, I'm a bit confused with the web stuff.
This is apparently realted to the `Home`, `Download`, etc pages.

**Comment by stefanv** [comment]
@soupault The website is generated by this repository, the docs separately (but using the same navbar and theme).

**Comment by soupault** [comment]
@stefanv I'm just curious, have you already discussed merging these two repositories (main and web-related) (https://github.com/blog/2233-publish-your-project-documentation-with-github-pages) ?
It could be a solution to https://github.com/scikit-image/scikit-image/issues/1500.

**Comment by stefanv** [comment]
Both our web page and documentation are compiled, so I don't think we
can use this solution.

**Comment by stefanv** [comment]
Cannot replicate on Chrome. We'll probably move over to a new theme soon, so not super problematic either way.
