### ISSUE TITLE
Website navigation is inconsistent

### ISSUE THREAD

**Issue by soupault** [scikit-image/skimage-web#40]
Consider following path:
1. http://scikit-image.org/;
2. Stay at the main page or goto `Download`/`Community Guidelines`;
3. In the header: `Gallery` leads to `dev`, `Documentation` leads to `stable` **???**;
4. Click on `Documentation` (is `stable`, remember?);
5. Now `Documentation` link in the bar leads to `dev`, as well as `Gallery`.

I guess this is the reason why users often report import issues.
We should fix links for `Gallery` and `Documentation` to point at the same version (preferably `stable`).

**Comment by stefanv** [comment]
(3) was chosen explicitly so that users will always get a demo of the latest capabilities.

(5) is incorrect

I agree that we have some work to do on making the website navigation more intuitive, though.  I have some hand-written notes on that from a designer who helped me review what we've got---I'm traveling at the moment, but remind me to add that online when I'm back home.

**Comment by stefanv** [comment]
At a bare minimum, we should highlight on the right which version of the docs the viewer is looking at.

**Comment by soupault** [comment]
(3) I understand, but the experience one could get is not the best. Looking forward to seeing the drafts you have.
(5) <- double checked with an empty cache (see the screen record at https://drive.google.com/open?id=0B64HTp-ELmbcLUZ3ZmFmb1pOX00).

**Comment by stefanv** [comment]
@soupault I meant (5) is incorrect as in "we should fix it", not as in "your report was incorrect".

**Comment by jni** [comment]
Regarding (5), I think this is related: #22. =D

**Comment by soupault** [comment]
To be precise, I haven't say anything bad about `dev` version of gallery. I'd rather agree that it helps users get acquainted with the new features before the new release is actually out.
Perhaps, there is a compromise solution to this: to expose both `latest` and `dev` versions of docs and gallery. But if the latter is conveniently available from the former, that will do for me.

As a most simple solution I'd suggest to highlight `latest (0.12)` and `dev` in the `Versions` box on the right, or maybe even split the versions block into 2: `latest` + `dev` move to the right top and put it right under the searchbox, and leave others (call them "Previous versions") where they are. If that's done, I'd prefer to have to have `latest (stable)` links for both Gallery and Documentation in the header (menu bar).

**Comment by soupault** [comment]
To be even more precise, maybe I did :). Either ways, the message should be clear.
As usual, we might get some inspiration from `sklearn` people: they show limited number of previous versions, and have a catchy box with the version number of the docs being viewed. As for `dev` versions, I think, it'd be better to follow our own approach.

**Comment by stefanv** [comment]
I agree that the documentation version should be more clearly displayed.  I'm somewhat ambivalent as to which version the gallery points to, although the idea was always to have it be a showcase of the latest functionality we include.

**Comment by jni** [comment]
@stefanv if we start building pre-release wheels and conda packages, I'd be ok with leaving dev as the default. =)

**Comment by stefanv** [comment]
Fair enough :)

**Comment by soupault** [comment]
Has been fixed with https://github.com/scikit-image/skimage-web/commit/91751331845cdc9e286674925fff2b24d7e33fdc .
