### ISSUE TITLE
the search bar is not working.

### ISSUE THREAD

**Issue by sciunto** [scikit-image/skimage-web#60]
Reported here: https://forum.image.sc/t/search-not-working-on-website/25305

**Comment by ctrueden** [comment]
I also commented on the forum thread, but I am guessing the issue is that when you search for something for which there are no results, the search appears to run forever with the animated ellipses after "Searching" message. There are also some JavaScript console errors.

**Comment by jni** [comment]
> I am guessing the issue is that when you search for something for which there are no results, the search appears to run forever

This doesn't appear to be the case, because I just received a report (via email) that searching for `label` works on Chrome but not on Firefox.

**Comment by jni** [comment]
Based on the other comments in the thread, I think cross-site scripting might be the issue? That's something where different browsers and different networks might have an effect.

I'll admit that I never use the website search and always Google "scikit-image whatever-im-searching-for". Perhaps we should remove search altogether?

**Comment by soupault** [comment]
>I'll admit that I never use the website search and always Google "scikit-image whatever-im-searching-for".

Same for me. However, I remember @ahojnnes saying somewhere about using the search bar. Presumably, there are more than 1 user :).

**Comment by stefanv** [comment]
xref: https://github.com/sphinx-doc/sphinx/issues/6244

**Comment by stefanv** [comment]
Seems to work now.
