### ISSUE TITLE
Changing versions in Gallery leads to Documentation.

### ISSUE THREAD

**Issue by mkcor** [scikit-image/skimage-web#72]
Hello,

I have noticed this issue for a while. I'm finally taking a minute to report it. I searched existing (open and closed) issues and didn't find any reference to it; sorry if I missed it though.

If I want to navigate the latest (dev version) Gallery, which I often do, I find myself doing this one extra, counter-intuitive click.

### Steps to reproduce

0. Visit website https://scikit-image.org/.
1. Click "Gallery" (this takes you to https://scikit-image.org/docs/stable/auto_examples/).
2. Click "All versions" in the sidebar and select 'skimage dev.' Noooo! Now you're at https://scikit-image.org/docs/dev/ (which in practice amounts to "Documentation" since it's https://scikit-image.org/docs/dev/#).
3. So you have to click "Gallery" again to get https://scikit-image.org/docs/dev/auto_examples/index.html (which you expected at the previous step).

This holds for all version changes, not only 'skimage dev.'

**Comment by stefanv** [comment]
This was fixed by the switch to pydata-sphinx-theme.
