### ISSUE TITLE
Search bar bug: The right navbar is fetching dev version instead of the stable version 

### ISSUE THREAD

**Issue by rum1887** [scikit-image/skimage-web#83]
When you type a function on the right search bar, The request is sent to:
https://scikit-image.org/docs/**dev**/search.html?q=regionprops&check_keywords=yes&area=default

Whilst, when you type on the left search bar after visiting the documentation section, the request is sent to :
https://scikit-image.org/docs/**stable**/search.html?q=regionprops&check_keywords=yes&area=default

I have emphasised the difference in URLs. Dev and stable.
Change dev to stable while fetching results from the right search bar.

**Ways to reproduce :**
* Visit https://scikit-image.org/
* Type in any function name in the search bar at the top right corner
* See results. (Broken behaviour)

* Visit https://scikit-image.org/
* Click on the documentation tab
* Type in any function name in the search bar at the top left corner
* See the right results.

**Comment by soupault** [comment]
Hi @rum1887, thank you for reporting! That is clearly an inconsistency that should be fixed. My suggestion would be to always direct the users to the stable version.

**Comment by rum1887** [comment]
> Hi @rum1887, thank you for reporting! That is clearly an inconsistency that should be fixed. My suggestion would be to always direct the users to the stable version.

Hello @soupault , can you review the pr :)

**Comment by lagru** [comment]
Fixed in #82.
